<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       name="ud" >

  <xacro:include filename="$(find ubiquitous_display)/config/youbot_base_only.urdf.xacro" />

  <property name="pillar_height" value="0.5"/>
  <property name="pillar_radius" value="0.01"/>
  <property name="pillar_offset_x" value="0.2"/>
  <property name="pillar_offset_y" value="0.07"/>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <!-- Body -->
  <link name="pillars">
    <visual>
      <geometry>
        <cylinder length="${pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} ${pillar_offset_y} ${pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} ${pillar_offset_y} ${pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} -${pillar_offset_y} ${pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} -${pillar_offset_y} ${pillar_height/2}"/>
      <material name="black"/>
    </visual>
  </link>
  <joint name="base_to_pillars" type="fixed">
    <parent link="base_link"/>
    <child link="pillars"/>
  </joint>

  <link name="top_plate">
    <visual>
      <geometry>
       <box size="0.4 0.14 0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>
  <joint name="pillars_to_top_plate" type="fixed">
    <parent link="pillars"/>
    <child link="top_plate"/>
    <origin xyz="0 0 ${pillar_height}"/>
  </joint>

  <!-- base laser front -->
  <xacro:hokuyo_urg04_laser name="base_laser_front" parent="base" ros_topic="base_scan" update_rate="10" min_angle="-1.57" max_angle="1.57">
    <origin xyz="0.25 0 0.22" rpy="0 0 0"/>
  </xacro:hokuyo_urg04_laser>

</robot>
