<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       name="ud" >

  <xacro:include filename="$(find ubiquitous_display)/config/youbot_base_only.urdf.xacro" />

  <property name="bottom_pillar_height" value="0.2"/>
  <property name="top_pillar_height" value="0.4"/>
  <property name="pillar_radius" value="0.01"/>
  <property name="pillar_offset_x" value="0.2"/>
  <property name="pillar_offset_y" value="0.07"/>
  <property name="plate_len_x" value="0.5"/>
  <property name="plate_len_y" value="0.2"/>
  <property name="hokuyo_offset_x" value="0.25"/>
  <property name="hokuyo_offset_z" value="0.04"/>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <!-- Body -->
  <!-- Bottom part -->
  <link name="bottom_pillars_link">
    <visual>
      <geometry>
        <cylinder length="${bottom_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} ${pillar_offset_y} ${bottom_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${bottom_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} ${pillar_offset_y} ${bottom_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${bottom_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} -${pillar_offset_y} ${bottom_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${bottom_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} -${pillar_offset_y} ${bottom_pillar_height/2}"/>
      <material name="black"/>
    </visual>
  </link>
  <joint name="base_to_bottom_pillars_joint" type="fixed">
    <parent link="base_link"/>
    <child link="bottom_pillars_link"/>
  </joint>

  <link name="bottom_plate_link">
    <visual>
      <geometry>
        <box size="${plate_len_x} ${plate_len_y} 0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>
  <joint name="bottom_pillars_to_bottom_plate_joint" type="fixed">
    <parent link="bottom_pillars_link"/>
    <child link="bottom_plate_link"/>
    <origin xyz="0 0 ${bottom_pillar_height}"/>
  </joint>

  <!-- Top part -->
  <link name="top_pillars_link">
    <visual>
      <geometry>
        <cylinder length="${top_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} ${pillar_offset_y} ${top_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${top_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} ${pillar_offset_y} ${top_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${top_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} -${pillar_offset_y} ${top_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${top_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} -${pillar_offset_y} ${top_pillar_height/2}"/>
      <material name="black"/>
    </visual>
  </link>
  <joint name="bottom_plate_to_top_pillars_joint" type="fixed">
    <parent link="bottom_plate_link"/>
    <child link="top_pillars_link"/>
  </joint>

  <link name="top_plate_link">
    <visual>
      <geometry>
        <box size="${plate_len_x} ${plate_len_y} 0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>
  <joint name="top_pillars_to_top_plate_joint" type="fixed">
    <parent link="top_pillars_link"/>
    <child link="top_plate_link"/>
    <origin xyz="0 0 ${top_pillar_height}"/>
  </joint>

  <!-- base laser front -->
  <xacro:hokuyo_urg04_laser name="base_laser_front" parent="bottom_plate" ros_topic="base_scan" update_rate="10" min_angle="-1.57" max_angle="1.57">
    <origin xyz="${hokuyo_offset_x} 0 ${hokuyo_offset_z}" rpy="0 0 0"/>
  </xacro:hokuyo_urg04_laser>

</robot>
